name: infra_deploy
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  terraform_initandplan:
    name:  terraform init and plan
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.1
     
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: b1da5deb-01fc-4477-b34d-8a8fbbc81eae
        tenant-id: 90c2d389-705b-4327-885c-ab24afe7aa51
        subscription-id: 77312bdf-fff4-4e77-9d06-5e69870a682c

      
    - name: Terraform Init
      id: init
      run: terraform init -input=false  
      working-directory: environments/dev
      
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      working-directory: environments/dev
      
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: environments/dev

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
      working-directory: environments/dev

  terraform_initandapply:
    name:  terraform init and apply
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.1
     
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: b1da5deb-01fc-4477-b34d-8a8fbbc81eae
        tenant-id: 90c2d389-705b-4327-885c-ab24afe7aa51
        subscription-id: 77312bdf-fff4-4e77-9d06-5e69870a682c

      
    - name: Terraform Init
      id: init
      run: terraform init -input=false  
      working-directory: environments/dev

    - name: terraform apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: environments/dev
      
      
